export const ADD_BUN_ITEM = 'ADD_BUN_ITEM';
export const DELETE_BUN_ITEM = 'DELETE_BUN_ITEM';

export const ADD_COMPONENT_ITEM = 'ADD_COMPONENT_ITEM';
export const DELETE_COMPONENT_ITEM = 'DELETE_COMPONENT_ITEM';

export const UPDATE_CONSTRUCTOR_LIST="UPDATE_CONSTRUCTOR_LIST";